// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcI2FKKgoOrW6iAgBUUikY_nqek6J9Xro',
    appId: '1:284574204967:web:38c60e6dd2ccec7e9c7a02',
    messagingSenderId: '284574204967',
    projectId: 'assessment-4ab1b',
    authDomain: 'assessment-4ab1b.firebaseapp.com',
    storageBucket: 'assessment-4ab1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsbP38MB-geRTbKIERgBJcJp6kwXwNrWs',
    appId: '1:284574204967:android:3335d937c17883c99c7a02',
    messagingSenderId: '284574204967',
    projectId: 'assessment-4ab1b',
    storageBucket: 'assessment-4ab1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTIqsedG6JifB8KvcdkTuDewbDjFoacII',
    appId: '1:284574204967:ios:77fa5b11338f507f9c7a02',
    messagingSenderId: '284574204967',
    projectId: 'assessment-4ab1b',
    storageBucket: 'assessment-4ab1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
